# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fd1074be1fbe2c1370c1107a96ae6e01454fbbccfa476b1f171b93789e1e58524b06da497cf16489ab14894e0d9a830e0a86519c11bd05559fe2e3db0af41a6

test:
  secret_key_base: f8481a3f0d672ab35958aa643bacb1fac7c406f11779be8929fd07d1f9758b72eb592aeb24b7ea32ae3e366cb94c198d83b13b8c243d9ddc1bf961646b0b38eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
